# Generated by Django 4.2.7 on 2026-02-11 18:52

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(help_text='Unique employee identifier (e.g., EMP001)', max_length=20, unique=True, verbose_name='Employee ID')),
                ('full_name', models.CharField(help_text="Employee's full name", max_length=200, verbose_name='Full Name')),
                ('email', models.EmailField(help_text="Employee's email address", max_length=254, unique=True, validators=[django.core.validators.EmailValidator()], verbose_name='Email Address')),
                ('department', models.CharField(help_text='Department name (e.g., IT, HR, Sales)', max_length=100, verbose_name='Department')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'Employees',
                'db_table': 'employees',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Attendance date', verbose_name='Date')),
                ('status', models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent')], help_text='Attendance status (Present/Absent)', max_length=10, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='core.employee', verbose_name='Employee')),
            ],
            options={
                'verbose_name': 'Attendance',
                'verbose_name_plural': 'Attendances',
                'db_table': 'attendances',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['employee', 'date'], name='attendances_employe_993bac_idx'), models.Index(fields=['date'], name='attendances_date_234e8d_idx')],
                'unique_together': {('employee', 'date')},
            },
        ),
    ]
